name: Auto approve

on: 
  create:
    branches: ['cherry-pick*']   
  
jobs:
  auto-approve:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: hmarr/auto-approve-action@v3


