name: Auto approve

on:   
  pull_request:
    branches:
      - mt-main
    types: 
      - opened

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    if: github.actor == 'dependabot[bot]' || github.ref == 'refs/heads/cherry-pick*'
    steps:
      - uses: hmarr/auto-approve-action@v3


