name: PR to Release Branch

on:
  push:
    branches:
      - main

jobs:
  cherry-pick:
    name: Cherry Pick
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the latest code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
          
      - name: Automatic Cherry Pick
        uses: vendoo/gha-cherry-pick@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
