name: Pull Request to Mt-Main

on:
  pull_request:
    branches:
      - main
    types: ["closed"]

jobs:
  cherry_pick:
    runs-on: ubuntu-latest
    name: Cherry pick
    if: github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Cherry pick
        id: new-issue
        uses: carloscastrojumo/github-cherry-pick-action@v1.0.1
        with:
          branch: mt-main
          labels: cherry-pick   
      - run: |
          echo "${{ steps.new-issue.outputs.data }}"
          echo "${{ steps.new-issue.outputs.number }}" 
          echo "${{ steps.new-issue.outputs.html_url }}"
    
        
