name: Pull Request to Mt-Main

on:
  pull_request:
    branches:
      - main
    types: ["closed"]

jobs:
  cherry_pick:
    name: Create Pull Request
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
    - uses: actions/checkout@v3

    - name: Open Pull Request
      id: open-pr
      uses: repo-sync/pull-request@v2
      with:
        destination_branch: "mt-main"
        pr_label: "cherry-pick"
        pr_allow_empty: true

    - name: Auto Approve Pull Request
      uses: hmarr/auto-approve-action@v3
      with:
        pull-request-number: ${{steps.open-pr.outputs.pr_number}}

            
    
        
