name: Pull Request to MT-Main

on:
  pull_request:
    branches:
      - main
    types: ["closed"]

jobs:
  cherry_pick:
    runs-on: ubuntu-latest
    name: Cherry pick
    if: github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Cherry pick
        id: new-issue
        uses: carloscastrojumo/github-cherry-pick-action@v1.0.1
        with:
          branch: mt-main
          labels: cherry-pick   
          author: AvantiServiceAccount <AvantiServiceAccount@users.noreply.github.com>
          committer: AvantiServiceAccount <AvantiServiceAccount@users.noreply.github.com>

      - name: Auto Approve Pull Request - Github Actions User
        uses: hmarr/auto-approve-action@v3
        with:
          pull-request-number: ${{ steps.new-issue.outputs.outputs.data.number }}
    
      - name: Auto Approve Pull Request - Avanti Team User
        uses: hmarr/auto-approve-action@v3
        with:
          pull-request-number: ${{ steps.new-issue.outputs.outputs.data.number }}
          github-token: ${{ secrets.AVANTI_TEAM_USER }}
    
        
